/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddRecipeForm: typeof import('./src/components/AddRecipeForm.vue')['default']
    AppHeaderBar: typeof import('./src/components/AppHeaderBar.vue')['default']
    DesktopSettingsFab: typeof import('./src/components/DesktopSettingsFab.vue')['default']
    FilterModal: typeof import('./src/components/FilterModal.vue')['default']
    IngredientsCard: typeof import('./src/components/IngredientsCard.vue')['default']
    OverviewPanel: typeof import('./src/components/OverviewPanel.vue')['default']
    OverviewToolbar: typeof import('./src/components/OverviewToolbar.vue')['default']
    PlannerPanel: typeof import('./src/components/PlannerPanel.vue')['default']
    ProfilePanel: typeof import('./src/components/ProfilePanel.vue')['default']
    RecipeDetailCard: typeof import('./src/components/RecipeDetailCard.vue')['default']
    RecipeHero: typeof import('./src/components/RecipeHero.vue')['default']
    RecipeList: typeof import('./src/components/RecipeList.vue')['default']
    RecipeMetaInfo: typeof import('./src/components/RecipeMetaInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SegmentedToggle: typeof import('./src/components/SegmentedToggle.vue')['default']
    StepsCard: typeof import('./src/components/StepsCard.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UFileUpload: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FileUpload.vue')['default']
    USelect: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USwitch: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
  }
}
